fragment PostParts on Post {
  __typename
  title
  author
  pubDatetime
  modDatetime
  slug
  featured
  draft
  tags
  description
  body
}

fragment Post_mdxParts on Post_mdx {
  __typename
  title
  author
  pubDatetime
  modDatetime
  slug
  featured
  draft
  tags
  description
  body
}
